/**
 * src/services/blockchain/signatureService.js
 * Cryptographic signatures for system-level data validation
 */

const { ethers } = require('ethers');
const logger = require('../../utils/logger');

/**
 * Sign a data hash using the system private key
 * This provides proof that the data was generated by the authorized server.
 * @param {string} hash - Hex SHA256 hash or bytes32
 * @returns {string} signature - Hex signature
 */
exports.signHash = async (hash) => {
    try {
        const privateKey = process.env.DEPLOYER_PRIVATE_KEY;
        if (!privateKey) throw new Error('Signing key not found');

        const wallet = new ethers.Wallet(privateKey);
        const signature = await wallet.signMessage(ethers.getBytes(hash));

        return signature;
    } catch (err) {
        logger.error(`Signature error: ${err.message}`);
        throw err;
    }
};

/**
 * Verify a system signature
 * @param {string} hash - The data hash
 * @param {string} signature - The signature to verify
 * @returns {boolean}
 */
exports.verifySystemSignature = (hash, signature) => {
    try {
        const expectedAddress = process.env.SYSTEM_WALLET_ADDRESS || new ethers.Wallet(process.env.DEPLOYER_PRIVATE_KEY).address;
        const recoveredAddress = ethers.verifyMessage(ethers.getBytes(hash), signature);

        return recoveredAddress.toLowerCase() === expectedAddress.toLowerCase();
    } catch (err) {
        return false;
    }
};

/**
 * Create an EIP-712 typed signature for a Result object
 * This is the "Strongest" way to sign data for blockchain compatibility.
 */
exports.signResultTyped = async (resultData) => {
    try {
        const privateKey = process.env.DEPLOYER_PRIVATE_KEY;
        const wallet = new ethers.Wallet(privateKey);

        const domain = {
            name: 'MCQ Pro Platform',
            version: '1',
            chainId: process.env.CHAIN_ID || 31337, // Default Hardhat
            verifyingContract: process.env.CONTRACT_ADDRESS
        };

        const types = {
            Result: [
                { name: 'studentId', type: 'string' },
                { name: 'score', type: 'uint256' },
                { name: 'timestamp', type: 'uint256' },
                { name: 'resultHash', type: 'bytes32' }
            ]
        };

        const value = {
            studentId: resultData.studentId.toString(),
            score: Math.floor(resultData.score),
            timestamp: Math.floor(new Date(resultData.createdAt).getTime() / 1000),
            resultHash: resultData.blockchainHash
        };

        return await wallet.signTypedData(domain, types, value);
    } catch (err) {
        logger.error(`Typed signing error: ${err.message}`);
        return null;
    }
};
